### ISSUE TITLE
Nuget v1.04, UWP 14393, mediaplayerelement, http flv streaming or rtmp streaming, video stops as soon as pressing left or right direction key on keyboard

### ISSUE THREAD

**Issue by TaoziDB** [zhengbomo/FFmpegInterop#1]
Nuget v1.04, UWP 14393, Visual Studio 2017, MediaPlayerElement, playing http flv streaming or rtmp streaming, video plays as normal, but stops as soon as pressing left or right direction key on keyboard.

Another situation is that if no user interruption, the video will automatically stop in about 3 - 5 minutes.

Curiously, this only happens on release mode, if on debug mode, video will not stop when left or right direction key is pressed or in about 3-5 minutes.

Can you point me to the right direction?

I know FFmpeginterop and ffmpeg builds in Nuget v1.04 package are very old, but I failed to build myself.

If someone knows this bug existed for old version and newer version of FFmpeginterop and ffmpeg have since fixed this, please let me know, then I guess I need try to build newest version myself again.

[Update] If I enable "Compile with .NET Native tool chain" for debug mode, the same stop bugs will happen, since in release mode, "Compile with .NET Native tool chain" is enabled per windows store requirement, which means "Compile with .NET Native tool chain" is the problem, what to do now?

**Comment by zhengbomo** [comment]
sorry，i doesnot work well，i have no time to manage it

发自我的 Windows10

**Comment by TaoziDB** [comment]
In summary, per  @lukasf [Issue #160 comment](https://github.com/Microsoft/FFmpegInterop/issues/160#issuecomment-334765814) the solution is to store the FFmpegInteropMSS object to avoid GC. DO NOT USE local variable.

It seems GC in Release mode is more brutal than GC in Debug mode.
